In [2]:
pwd

'C:\\Users\\Ruthvik'

In [5]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

# Step 1: Load and preprocess the dataset
data = np.genfromtxt('wdbc.data.mb.csv', delimiter=',')
X = data[:, :-1]  # Features
y = data[:, -1]   # Class labels

# Step 2: Split the dataset into training (70%) and testing (30%) sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Step 3: Distance calculation module
def euclidean_distance(x1, x2):
    return np.sqrt(np.sum((x1 - x2)**2))

# Step 4: Class assignment module using kNN
def kNN_predict(X_train, y_train, X_test, k):
    predictions = []
    for test_sample in X_test:
        distances = [euclidean_distance(test_sample, train_sample) for train_sample in X_train]
        k_indices = np.argsort(distances)[:k]
        k_nearest_labels = [y_train[i] for i in k_indices]
        most_common = np.bincount([1 if label == 1 else 0 for label in k_nearest_labels]).argmax()
        predictions.append(1 if most_common == 1 else -1)
    return predictions

# Step 5: Test kNN for different values of k
k_values = [1, 3, 5, 7, 9]
for k in k_values:
    y_pred = kNN_predict(X_train, y_train, X_test, k)
    accuracy = accuracy_score(y_test, y_pred)
    cm = confusion_matrix(y_test, y_pred)
    print(f'For k={k}:')
    print(f'Accuracy: {accuracy:.4f}')
    print('Confusion Matrix:')
    print(cm)
    print('-' * 50)


For k=1:
Accuracy: 0.9185
Confusion Matrix:
[[102   8]
 [  7  67]]
--------------------------------------------------
For k=3:
Accuracy: 0.9457
Confusion Matrix:
[[106   4]
 [  6  68]]
--------------------------------------------------
For k=5:
Accuracy: 0.9457
Confusion Matrix:
[[104   6]
 [  4  70]]
--------------------------------------------------
For k=7:
Accuracy: 0.9565
Confusion Matrix:
[[106   4]
 [  4  70]]
--------------------------------------------------
For k=9:
Accuracy: 0.9511
Confusion Matrix:
[[106   4]
 [  5  69]]
--------------------------------------------------
